spring:
  application:
    name: dipendenti-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dipendenti
    username: azienda
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    producer:
      bootstrap-server: localhost:9092
      group-id: order-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.azienda.dipendenti.kafka.OrderConfirmation

  mail:
    host: smtp.gmail.com
    port: 587
    username: fggabrielito@gmail.com
    password: xsal rvqs pwyq dkgn
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    debug: true
server:
  port: 8072

application:
  config:
    user-url: http://localhost:8070/api/v1/utenti
    prodotti-url: http://localhost:8071/api/v1/prodotti
    payment-url: http://localhost:8073/api/v1/payments
